name: My Test Workflow

#define trigger event
on: [push]

#jobs run in parallel by default, each runs steps in sequence
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello, Github Actions!"
            