name: My Test Workflow

#define trigger event
on: [push]

#jobs run in parallel by default, each runs steps in sequence
jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, Github Actions!"
            
    needs: [say-hello]
    runs-on: ubuntu-lateststeps
    steps:
        - name: Check out this repo
          uses: actions/checkout@v3
          
        - name: Install dependencies
          run: sudo apt install -y build-essential python3
          
          
        - run: pwd
        
        - name: Run test
          run: python3 test.py